version: '3.8'

services:
  weather_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - UVICORN_CMD=uvicorn weather_api:app --host 0.0.0.0 --port 80 --reload
